version: 0.0
os: linux
files:
  - source: /
    destination: /mahesh/new_chatapp
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 500
      runas: root
  AfterInstall:
    - location: scripts/django.sh
      timeout: 800
      runas: root
